### ISSUE TITLE
TypeError in request-plugin-cache-memory with memoryConstructor

### ISSUE THREAD

**Issue by davakh** [TinkoffCreditSystems/tinkoff-request#18]
I've got an error about lruCache constructor while trying to use this library with `memoryCache` plugin. I used it without arguments, so my code for request looks like this:

**Used code**
```
const someRequest = request([
  memoryCache(),
  http()
]);
```

**Console output:**
```
    var lruCache = memoryConstructor(tslib_1.__assign({}, lruOptions, { stale: true }));
                   ^

TypeError: Class constructor LRUCache cannot be invoked without 'new'
```

**Used versions**  

`@tinkoff/request-core`:
  version: 0.8.1
 
`@tinkoff/request-plugin-cache-memory`
  version: 0.8.2

`@tinkoff/request-plugin-protocol-http`
  version: 0.10.0

**Comment by Tom910** [comment]
Hi, thanks for your report and i fixed this bug in `@tinkoff/request-plugin-cache-memory@0.8.4`
